name: CheckXcodeVersion

on:
  workflow_dispatch:

jobs:
  check-xcode:
    runs-on: macos-latest

    steps:
      - name: Check if Xcode 16.4 is installed
        run: |
          if [ -d "/Applications/Xcode_16.4.app" ]; then
            echo "✅ Xcode 16.4 is installed"
          else
            echo "❌ Xcode 16.4 is NOT installed"
          fi
